language: node_js
node_js:
  - "6.0.0"
script: npm run travis
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true # git stash --all fails for some reason https://github.com/travis-ci/travis-ci/issues/5854
  on:
    tags: true
    condition: ${TRAVIS_TAG} =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
